% --------------------------- CHAPTER 2: DIRECT SOLUTION OF Ax=b --------------------------
% Attendant to the text <a href="matlab:NRweb">Numerical Renaissance: simulation, optimization, & control</a>
% Files in Chapter 2 of <a href="matlab:help NRC">Numerical Renaissance Codebase 1.0</a>:
%   Gauss              - function [B,A] = Gauss(A,B,n)
%   GaussLU            - function [B] = GaussLU(Amod,B,n)
%   GaussTest          - script <a href="matlab:GaussTest">GaussTest</a>
%   GaussPP            - function [B,A,p] = GaussPP(A,B,n)
%   GaussPLU           - function [C] = GaussPLU(Amod,B,p,n)
%   GaussPPTest        - script <a href="matlab:GaussPPTest">GaussPPTest</a>
%   Example_2_1        - script <a href="matlab:Example_2_1">Example_2_1</a>
%   Inv                - function [A]=Inv(A)
%   InvTest            - script <a href="matlab:InvTest">InvTest</a>
%   GaussCP            - function [X,A,p,q] = GaussCP(A,B,n)
%   GaussPLUQT         - function [B] = GaussPLUQT(Amod,B,p,q,n)
%   GaussCPTest        - script <a href="matlab:GaussCPTest">GaussCPTest</a>
%   Thomas             - function [G,a,b,c] = Thomas(a,b,c,G,n)
%   ThomasLU           - function [G] = ThomasLU(a,b,c,G,n)
%   ThomasTest         - script <a href="matlab:ThomasTest">ThomasTest</a>
%   ThomasTT           - function [G] = ThomasTT(a,b,c,G,n)
%   ThomasTTTest       - script <a href="matlab:ThomasTTTest">ThomasTTTest</a>
%   Circulant          - function [G,a,b,c,d,e] = Circulant(a,b,c,G,n)
%   CirculantLU        - function [G] = CirculantLU(a,b,c,d,e,G,n)
%   CirculantTest      - script <a href="matlab:CirculantTest">CirculantTest</a>
%   ThomasParallel     - function [g] = ThomasParallel(a,b,c,g,n,p)
%   ThomasParallelTest - script <a href="matlab:ThomasParallelTest">ThomasParallelTest</a>
%   GaussEchelon       - function [A,p,r,v] = GaussEchelon(A)
%   GaussEchelonTest   - script <a href="matlab:GaussEchelonTest">GaussEchelonTest</a>
% <a href="matlab:help NRchap01"><-previous</a> ---------- please read the <a href="matlab:help NRcopyleft">copyleft</a>, and please <a href="matlab:help NRsupport">support</a> us! ----------- <a href="matlab:help NRchap03">next-></a>
