# This is a general use makefile for librobotcontrol projects written in C.
# Just change the target name to match your main source code filename.
TARGET = marco_colon_HW5
# compiler and linker binaries
CC              := gcc
LINKER          := gcc
***
